import { IDayScheduleRepository } from '../../domain/interfaces/repositories/IDayScheduleRepository';
import { DayScheduleItemEntity } from '../../domain/entities/DayScheduleItem';

// ER移行完了までの読み取り専用ダミー。管理画面モック（9件）に準拠。
const DAY_SCHEDULE_ITEMS: DayScheduleItemEntity[] = [
  {
    id: 1,
    type: 'ceremony',
    type_label: '開会式',
    start_time: '08:30',
    end_time: '09:00',
    venue: 'コートA',
    meeting_place: null,
    related_competition_name: null,
    remarks: null,
    scheduled_post: '即時公開',
    order: 1,
  },
  {
    id: 2,
    type: 'competition',
    type_label: '競技',
    start_time: '09:10',
    end_time: '10:10',
    venue: 'コートB',
    meeting_place: null,
    related_competition_name: '走れ！〇人〇脚！',
    remarks: null,
    scheduled_post: '即時公開',
    order: 2,
  },
  {
    id: 3,
    type: 'gathering',
    type_label: '集合',
    start_time: '10:15',
    end_time: '10:25',
    venue: null,
    meeting_place: '集合場所A',
    related_competition_name: null,
    remarks: 'ガチンコ綱引き前の集合',
    scheduled_post: '09:50',
    order: 3,
  },
  {
    id: 4,
    type: 'competition',
    type_label: '競技',
    start_time: '10:30',
    end_time: '11:30',
    venue: 'コートA',
    meeting_place: null,
    related_competition_name: 'ガチンコ綱引き',
    remarks: null,
    scheduled_post: '即時公開',
    order: 4,
  },
  {
    id: 5,
    type: 'competition',
    type_label: '競技',
    start_time: '11:40',
    end_time: '12:20',
    venue: 'コートA',
    meeting_place: null,
    related_competition_name: '四天王ドッチボール',
    remarks: null,
    scheduled_post: '即時公開',
    order: 5,
  },
  {
    id: 6,
    type: 'break',
    type_label: '昼休み',
    start_time: '12:20',
    end_time: '13:20',
    venue: '各自',
    meeting_place: null,
    related_competition_name: null,
    remarks: null,
    scheduled_post: '即時公開',
    order: 6,
  },
  {
    id: 7,
    type: 'competition',
    type_label: '競技',
    start_time: '13:30',
    end_time: '14:10',
    venue: 'コートB',
    meeting_place: null,
    related_competition_name: '紙飛行機飛ばし',
    remarks: null,
    scheduled_post: '13:00',
    order: 7,
  },
  {
    id: 8,
    type: 'competition',
    type_label: '競技',
    start_time: '14:20',
    end_time: '15:30',
    venue: 'コートC',
    meeting_place: null,
    related_competition_name: '学科別対抗リレー',
    remarks: null,
    scheduled_post: '即時公開',
    order: 8,
  },
  {
    id: 9,
    type: 'ceremony',
    type_label: '閉会式',
    start_time: '15:45',
    end_time: '17:00',
    venue: 'コートA',
    meeting_place: null,
    related_competition_name: null,
    remarks: null,
    scheduled_post: '即時公開',
    order: 9,
  },
];

export function createDayScheduleRepository(): IDayScheduleRepository {
  return {
    async findAll() {
      return [...DAY_SCHEDULE_ITEMS];
    },
  };
}
